### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by Xant1k** [varjolintu/keepassxc-browser#1]
After install extension i get error in the console extension log:
`console.log("Connecting to native messaging host " + keepass.nativeHostName)`
and then i can't connect to database.
Please fix it

**Comment by varjolintu** [comment]
I need more info. Have you got the .json in the correct place and the extension ID inside it matches the chromeKeePassXC extension ID? Currently I don't have a installation script of the JSON in the repository, but it will be available shortly.

And are you using the KeePassXC version which supports this extension? You can get it [here](https://github.com/varjolintu/keepassxc/releases/tag/2.1.4-browser).

Please note that this is still an experimental feature not yet officially supported with KeePassXC.

**Comment by Xant1k** [comment]
latest install
`_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setPopup: No tab with id: 115.
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:29:25)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:91:17
    at Object.keepass.isConfigured (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/keepass.js:552:3)
    at Object.browserAction.showDefault (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:79:10)
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:16:17)
    at Object.browserAction.removeRememberPopup (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:203:18)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/init.js:65:16
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setIcon: No tab with id: 115.
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setPopup: No tab with id: 138.
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:29:25)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:91:17
    at Object.keepass.isConfigured (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/keepass.js:552:3)
    at Object.browserAction.showDefault (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:79:10)
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:16:17)
    at Object.browserAction.removeRememberPopup (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:203:18)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/init.js:65:16
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setIcon: No tab with id: 138.
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setPopup: No tab with id: 130.
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:29:25)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:91:17
    at Object.keepass.isConfigured (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/keepass.js:552:3)
    at Object.browserAction.showDefault (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:79:10)
    at Object.browserAction.show (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:16:17)
    at Object.browserAction.removeRememberPopup (chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/browserAction.js:203:18)
    at chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/background/init.js:65:16
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setIcon: No tab with id: 130.
`

**Comment by varjolintu** [comment]
I need more info. What version of Chrome are you using? Are these errors shown on what page? Does it crash the extension or what happens? Thanks.

**Comment by mauron85** [comment]
Hi @varjolintu. I've just compiled keepassxc from branch `2.1.4-browser-beta1` and also installed [keepassxc-browser]() Chrome extension. I see Browser extension (Native Messaging) in Application Setting and it's enabled. My problem is that I cannot connect to keepassxc database from Chrome extension. Clicking on 'Connect' doesn't do anything. Can you give me some suggestion what else can I try. Many thanks.

My env:
Ubuntu 16.04 64bit
Chrome: version 59.0.3071.104 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
@mauron85. Have you installed the .json files Native Messaging needs? You can find the install script and .json files from the main directory if you cloned or saved the sources.

**Comment by mauron85** [comment]
First I must admit that after reading [your comment](https://github.com/varjolintu),  I was under wrong assumption that I don't need keepassx-proxy.
>... **The latter method** solves the issue but requires additional application (keepassxc-proxy, under development) between the KeePassXC and keepassxc-browser.

But with UDP method you mean `KeePassHTTP`, which is already part of keepassxc. Right? So if I want to use Native Messaging I have to use proxy.

Anyway I installed keepassxc-proxy.  There was problem with installing script - it would pass the [line 96 ](https://github.com/varjolintu/keepassxc-browser/blob/master/install.sh#L96) `KEEPASSXC_PATH="$(command -v keepassxc)"`. I guess `command -v` works only for programs installed in common $PATH.

So I had manually copied manifest to correct Chrome folder. And it worked, meaning proxy dialog popped up right after Chrome start.

But I didn't succeeded with connection to KeepassXC db from Chrome extension. There were some messages in proxy dialog though.

**Comment by varjolintu** [comment]
To make things clear:

The beta1 release only works with keepassxc-browser extension. I'm just releasing beta2 release which also works with keepassxc-proxy. UDP method is not related to KeePassHTTP. 

Also keepassxc-proxy project is still under development. That's clearly an error in the install script. I'll fix it :)

Shortly: If you want to use the keepassxc-proxy, wait half an hour. But beta1 should work straight with the browser extension too.

**Comment by mauron85** [comment]
Ok, I'll wait.

Still missing the big picture, but getting into it. ;-)

How I understand, now there are 3 methods how to connect to keepassxc from browser exstention(s). 
1. Former KeePassHTTP, 
2. UDP 
3. Native Extensions (requires proxy)

2. 3. are both your implementation. 
But one can use any of those 3 at will. Correct?

If so, where is configuration dialog for UDP method? I see only `Enable KeepassHTTP server` under `Browser intregration` and `Enable KeepassXC browser extension` under `Browser extension(chromeKeepassXC)`

Sorry for asking trivial questions, but I hate when I don't understand problem completely. ;-

FYI I added another small issue with proxy script in my previous comment.

**Comment by varjolintu** [comment]
There are three methods:
1) Former KeePassHTTP
2) Native Messaging with keepassxc-browser extension (straight connection to KeePassXC)
3) Native Messaging with keepassxc-proxy and keepassxc-browser extension (keepassxc-proxy transfer the messages between keepassxc-browser and KeePassXC so Native Messaging API doesn't interact with KeePassXC and closes it without unsaved changes)

The UDP configuration dialog can be found from beta2 release. It's released so give it a try :)

**Comment by mauron85** [comment]
ok. just built keepassxc from tag 2.1.4-browser-beta2 with:
```
cmake -DWITH_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_XC_HTTP=ON -DWITH_XC_BROWSER=ON -DWITH_XC_AUTOTYPE=ON ..
```

After I check 'Enable KeepassXC browser extension` it opens and start listening on UDP port 19700

But keepassxc-browser extension installed [from web Chrome Store](https://chrome.google.com/webstore/detail/keepassxc-browser/iopaggbpplllidnfmcghoonnokmjoicf) won't connect to db. Just nothing happens. Do I need keepassx-browser from github ?

**Comment by varjolintu** [comment]
If you use the keepassxc-browser directly with KeePassXC, ensure the path is correct in the installed .json file. If it is, KeePassXC should launch at the same time you start your browser. If that doesn't happen the path is probably wrong.

So don't start KeePassXC before starting the browser. With the proxy it doesn't matter if KeePassXC is already launched.

Big thanks bringing this kind of problems in to public. It really helps to finish the feature if something is clearly working incorrectly.

**Comment by mauron85** [comment]
Ok, I've updated `~/.config/google-chrome/NativeMessagingHosts/com.varjolintu.keepassxc_browser.json`
to:
```
{
  "name": "com.varjolintu.keepassxc_browser",
  "description": "KeepassXC integration with Chrome with Native Messaging support",
  "path" : "/usr/local/bin/keepassxc",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
    "chrome-extension://fhakpkpdnjecjfceboihdjpfmgajebii/"
  ]
}
```

Now keepassxc is starting at the same time as Chrome. But it doesn't connect to database. 

Quote from https://developer.chrome.com/extensions/nativeMessaging
>Chrome starts the host in a separate process and communicates with it using standard input and standard output streams.

But I thought keepassxc is using UDP not standartd input/output streams. How can this work. Or is there any other json you're talking about?

**Comment by mauron85** [comment]
Not sure if it's related, but attaching to keepassw PID with systrace and then clicking on 'Connect' generate lot of these:

```
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19699) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19636) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19555) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19484) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19259) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19240) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}, {fd=19, events=POLLIN}, {fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=25, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}, {fd=32, events=POLLIN}, {fd=33, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=37, events=POLLIN}, {fd=38, events=POLLIN}, {fd=40, events=POLLIN}], 19, 19140) = 1 ([{fd=7, revents=POLLIN}])
read(7, "\1\0\0\0\0\0\0\0", 16)         = 8
recvmsg(4, 0x7fff6cbd0030, 0)           = -1 EAGAIN (Resource temporarily unavailable)
```

**Comment by mauron85** [comment]
I think I understand now how it works and I guess my description of methods was wrong.

There are 2 new methods and **both of them** are using Chrome NativeMessaging.

Method 1.
When KeepassXC (must be built with `WITH_XC_BROWSER=ON`) is registered in NativeMessagingHosts json. Then chrome communicates directly with KeepassXC via stdin/stdout. Also Chrome automatically starts KeepassXC. There is problem with unsaved changes, because as Chrome starts KeepassXC automatically, it also kills KeepassXC on it's exit. That's why there is method 2.

Method 2:
Doesn't communicate directly with KeePassXC, but via keepasxc-proxy
When proxy is registered in NativeMessagingHosts json, then Chrome will communicate with proxy via stdin/stdout. Proxy then resend all it receives on stdin to KeePassXC via defined UDP port and also all responses back to Chrome via stdout. Proxy is started with Chrome and also killed with chrome, but killing proxy doesn't effect KeepassXC and that is why changes can be preserved.

**Comment by mauron85** [comment]
My assumptions seems to be correct. :-)

strace on keepassxc-proxy (python script) shows lot of:
```
futex(0xeee40c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 57159, {1498064236, 257049000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
write(6, "\0", 1)                       = 1
futex(0x7ffa910dd8e0, FUTEX_WAKE_PRIVATE, 1) = 1
recvmsg(4, 0x7ffd91bf8380, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, 0x7ffd91bf8380, 0)           = -1 EAGAIN (Resource temporarily unavailable)
write(6, "\0", 1)                       = 1
futex(0x7ffa910dd8e0, FUTEX_WAKE_PRIVATE, 1) = 1
```

And also `sudo tcpdump -i lo -vv` show lot of wrong udp checksums (where localhost.19700 is port configured in KeePassXC `Browser extension (Native Messaging)` :
```
18:58:51.036373 IP (tos 0x0, ttl 64, id 40890, offset 0, flags [DF], proto UDP (17), length 169)
    localhost.19700 > localhost.33516: [bad udp cksum 0xfea8 -> 0x3eac!] UDP, length 141
```

But finally it works. Now we need just polish. I've couple of suggestions :-)

1. make keepassxc-proxy just simple proxy without any dependency on python-tk. Showing dialogs should be responsibility of KeePassXC app.

2. keepassxc-proxy will bundled directly with KeePassXC app. Maybe we can write native alternative. And also creating `com.varjolintu.keepassxc_browser.json` would be responsobility of the app. 

That's it. By the way awesome work.

The question is why method 1. doesn't work for me.

**Comment by varjolintu** [comment]
You are 100%  correct about the methods. Maybe I should include them to the README. I think that would be really helpful.

I'm not sure if the Native Messaging host will work without a GUI. I have tried it before and it just didn't work correctly. But I'll give it a second try in the future. The UDP support is not finished yet so it will take a while to polish it. There's a timeout in the UDP socket in the python proxy. That might explain the messages. The polling events in the previous messages might be because of the Boost library. Its asynchronous method probably polls the stdin descriptor.

Thank you for the suggestions! I agree with all of them. So I still got some work to do :) But glad it works. I'll investigate the method 1 issue when I have some time. And I'll do it under Ubuntu. Thanks again.

**Comment by varjolintu** [comment]
@mauron85 
And now back to the original issue. My test machine is following:
Browser: Chromium version 58.0.3029.110 (Official Build) (64-bit)
2nd Browser: Google Chrome version 59.0.3071.104 (Official Build) (64-bit)
OS: Ubuntu 17.04
KeePassXC: 2.1.4-browser-beta2
keepassxc-browser: 0.1.10

When I build a debug version KeePassXC doesn't start. Release build works. But when database is not opened KeePassXC window is keeping popping up to the top. Connecting to database and receiving credentials work normally. I'm not sure why debug builds doesn't work but I will keep investigating the issue. In the meantime you can try if release build works for you?

**Comment by mauron85** [comment]
Are you talking about compiling KeePassXC with `-DCMAKE_BUILD_TYPE=Debug` ? from you git repo?
If so, what is the actual difference between `DEBUG` build type and not specified (production???) build type. I didn't found anything useful apart from configuration file being `keepassxc_debug.ini` vs `keepassxc.ini`.

**Comment by varjolintu** [comment]
This doesn't happen in macOS. Gotta investigate more.

**Comment by varjolintu** [comment]
Closing the issue because the version is pretty old and there are no responses.
