### ISSUE TITLE
can not connect keepassxc 

### ISSUE THREAD

**Issue by yunair** [varjolintu/keepassxc-browser#12]
I use chrome ver 60.0.3112.72 (Official Build) beta (64-bit) with keepassxc-browser  ver 0.2.6,
and official keepassxc v2.2.0
I use this mode `keepassxc-browser communicates directly with KeePassXC via stdin/stdout`

When I click reload button, keepassxc-browser give me a log "Timeout or not connected to KeePassXC"

Is there any way to get detail log for you? or any other solution to solve this problem?

**Comment by yunair** [comment]
I found this at chrome dev tools
`
keepass.js:683 Connecting to native messaging host com.varjolintu.keepassxc_browser
keepass.js:675 Failed to connect: Native host has exited.
keepass.js:739 Error 5: Timeout or not connected to KeePassXC
`
what should I do next?

**Comment by varjolintu** [comment]
The official KeePassXC does not yes work. You have to use [this](https://github.com/varjolintu/keepassxc/releases) branch.
