### ISSUE TITLE
FF extension requires FF57

### ISSUE THREAD

**Issue by duk3luk3** [varjolintu/keepassxc-browser#13]
FF57 is currently in beta (right?), and will be released in September (right?).

It would be nice if that was noted somewhere that is easy to find, like in the readme!

**Comment by varjolintu** [comment]
FF56 is in beta, FF57 is the current nightly. The stable version is released in November. The minimum version of the plugin is 56.0a1, but actually it even works with FF54 as a temporary extension (if you change the version from the manifest). But yes, the README was missing that info, I will update it :)

**Comment by varjolintu** [comment]
And please try the new release 0.2.8. I changed the minimum Firefox version to 55.0.

**Comment by duk3luk3** [comment]
Oh awesome, thanks! If you haven't seen, I've started work on modernising the backend for KeepassHTTP in KeepassXC: https://github.com/keepassxreboot/keepassxc/pull/850

With being able to install keepassxc-browser without any fuss, that means I can go ahead and rebase my work on your fork!
