### ISSUE TITLE
Support for OTP codes

### ISSUE THREAD

**Issue by sorcix** [varjolintu/keepassxc-browser#14]
KeepassXC is able to generate OTP codes, but we have to copy/paste those manually for now. It would be useful if keepassxc-browser could autofill these similar to how it works for usernames and passwords.

I would expect that keepassxc-browser can only access the generated codes, not the OTP secret.

Note that some websites ask for an OTP code with a separate form after logging in with a username and password (Github for example) but others (like [registry.be](https://registry.be)) have an OTP field in the same form that you have to fill right away.

**Comment by Generator** [comment]
There a PR on KeePassXC for custom placeholders for KeePassHTTP
See https://github.com/keepassxreboot/keepassxc/pull/1072

**Comment by varjolintu** [comment]
Nice. Thank you for the info.

**Comment by Mogost** [comment]
It would be Killer feature. Really.

**Comment by varjolintu** [comment]
When the PR is approved I will look into this :) It shouldn't be a hard thing to do.

**Comment by varjolintu** [comment]
The PR is now merged with this fork. The next step is adding the support to the browser extension. At first I'll put the OTP retrieval to the context menu.

**Comment by varjolintu** [comment]
Feature added with https://github.com/varjolintu/keepassxc-browser/commit/1f9b76178bc449858009b60076575a5defa20cb8.
