### ISSUE TITLE
automagically update browser icon as soon as database is properly connected

### ISSUE THREAD

**Issue by foss-** [varjolintu/keepassxc-browser#16]
Reproduce:

* launch browser
* keepassxc (beta) will open
* unlock correct database (there's a known issue in b8 which still needs to be addressed, opening an additional database everytime keepassxc is opened)

Currently:

* icon of keepassxc-browser shows red x indicating no connection
* reload of tab or opening new tab is required for the icon to update

Expected:

* as soon as there's a connection, icon should indicate that by no longer showing the red x

Could be solved by polling or another solution.

**Comment by varjolintu** [comment]
There's a few ways this could be possible. I will investigate the possible solution. The current implementation is not good enough. Although it behaves similar to passifox/chromeipass.

**Comment by varjolintu** [comment]
This feature is added in 0.2.9 which is just released. Enjoy :)
