### ISSUE TITLE
Not able to connect to DB in Firefox 57 - Mac Os

### ISSUE THREAD

**Issue by codergolem** [varjolintu/keepassxc-browser#17]
Hi,
I am trying to use the extension with Firefox 57 on a Mac OS but the DB is not found. In the wiki there is a screenshot with an additional menu for native browser extension (besides the normal browser integration menu), but this one does not appear in my KeepassXC app (2.2.0) - Any suggestion?

**Comment by varjolintu** [comment]
Are you using the fork build as readme suggests? The Native Messaging feature is not supported yet with the official build.

> For testing purposes, please use following unofficial KeePassXC [release](https://github.com/varjolintu/keepassxc/releases)'s.

**Comment by varjolintu** [comment]
@codergolem Please respond or the issue will be closed due to inactivity.

**Comment by snwflake** [comment]
Not OP, though same Problem.

* FF Nightly 57.0b2
* using your fork 2.2.0

Clicking on the extension in FF and hitting "Reload" brings KeePassXC to the front, but thats it.

**Comment by varjolintu** [comment]
I will check the behaviour with Nightly 57.0b2.

**Comment by codergolem** [comment]
Hello,
Sorry for the very late reply, should I close the issue then ?

**Comment by varjolintu** [comment]
If you got the problem solved, yes. Are you still having the same problem?
