### ISSUE TITLE
autofill for dialog boxes

### ISSUE THREAD

**Issue by Lalarian** [varjolintu/keepassxc-browser#18]
## Expected Behavior
Hello!
I'm using keepassxc(fork) since we first talked here and it's great so far. I just wonder if it would be possible to also include htaccess dialog boxes for autofilling.

## Current Behavior
When some sites (like for example my router login) open a dialog box for entering password, keepassxc-browser won't offer autofilling of credentials.

## Possible Solution-->
Lastpass did this, too, so I think it's possible.

## Debug Info

KeePassXC-browser - 0.2.8

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Betriebssystem: Ubuntu 17.04
CPU-Architektur: x86_64
Kernel: linux 4.10.0-32-generic

Aktivierte Erweiterungen:
- KeePassHTTP
- Native Messaging browser extension

Thank you for attention and support :)

**Comment by varjolintu** [comment]
This feature was working with chromeipass/passifox and it will be working with all browsers in the next version (0.30). If you want, you can use the sources from the dev branch to test it.
