### ISSUE TITLE
Extension "Checking Status" forever

### ISSUE THREAD

**Issue by rdd2** [varjolintu/keepassxc-browser#20]
Hi Sami, 
it's been a bumpy ride but I have decided to absolutely not give up this time. 

- Ubuntu GNOME 17.04 x64
- FF 55.02

I've now finally managed to build the keepassxc fork with browser support. My last big stumbling block was the .json file in ~/.mozilla/native-messaging-hosts which somehow pointed to /tmp/somethingorother/usr/bin/keepassxc

Changed that and now keepassxc actually launches with FF. However, now I just get a spinning wheel and "Checking status". What could this be?

![screenshot from 2017-09-19 22-56-43](https://user-images.githubusercontent.com/5879453/30615326-e7f1dc02-9d8e-11e7-91a7-281a8c9f6e4a.png)

Any help would be greatly appreciated. 

Tom

**Comment by varjolintu** [comment]
What is the browser extension version you are using? I assume it's 0.2.9. Could you debug the extension through about:debugging and see what the console prints?

Interesting that the binary points to a /tmp directory. Are you using an AppImage or did you do a make install or where do you originally ran the binary from for the first time?

**Comment by rdd2** [comment]
Yes, extension is 0.2.9 from Mozilla. And you're on the money with AppImage. Tried that, wouldn't launch with the browser. Then I started the glorious run I'm on now. So, I started debugging. Bear with me, no experience with this. When closing and relaunching keepassxc from the extension, I get this:

`Failed to connect: Unknown error  keepass.js:673:2
Error 5: Timeout or not connected to KeePassXC  keepass.js:733:2
Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:677:2
Server public key: XXXXXXXXXXXXXXXXXXXXXXXXXXX  keepass.js:527:4
Error 1: Database not opened  keepass.js:733:2`

I then enter the password and it goes to "Checking status". I've also tried with a fresh database just in case my bazillion passwords throw it off.

**Comment by rdd2** [comment]
Done some more:

- fresh database
- fresh FF profile 

`Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:677:2

Error: Invalid option asyncBlocking  WebRequest.jsm:90:15

DataError: Data provided to an operation does not meet requirements. (unknown)

Server public key: /nSUKMijKlNGOgda3f43OKRMCaeKRun9TO8iWl1Mi0s=  keepass.js:527:4

Error: Could not establish connection. Receiving end does not exist. undefined
Use of getAttributeNode() is deprecated. Use getAttribute() instead. disco-2b7543001e2229aa9265.js:1:659696

Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode”  browser.xul

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul

Key event not available on GTK2: key=“u” modifiers=“accel shift” id=“”  browser.xul`

**Comment by varjolintu** [comment]
What tab have you open when you click the popup and the state doesn't change? Does it help if you create a new tab and click the popup then? The log does show one error which shouldn't be there but that shouldn't create this issue.

**Comment by rdd2** [comment]
Tested it with different tabs. Always the same result.

**Comment by varjolintu** [comment]
Could you test this with the 0.3.0 release (download .crx from the releases page or load manifest.json as a temporary add-on)? If that has the same problem it's really strange. I can' reproduce this.

**Comment by rdd2** [comment]
Right, I loaded it as a temporary add-on. Same behaviour. I'm going to test this on a clean VM. Will get back to you with results.

**Comment by varjolintu** [comment]
The 0.3.0 release is in AMO.

**Comment by tcitworld** [comment]
I have the same issue with 0.3.0

**Comment by varjolintu** [comment]
@tcitworld Are you using an AppImage too? Try compile the sources by yourself.

**Comment by tcitworld** [comment]
Yup, just updated to latest sources with the same issue.

**Comment by varjolintu** [comment]
- Does the KeePassXC launch when you start the browser, or are you using a proxy application?
- If it doesn't, where does the com.varjolintu.keepassxc_browser.json path points to?
- If it does, what does the debug console say?
- Try to update to 0.3.1 which is just released

**Comment by tcitworld** [comment]
> Does the KeePassXC launch when you start the browser, or are you using a proxy application?

It does launch properly.

> If it does, what does the debug console say?

Quite odd stuff : 
```
Error 5: Timeout or not connected to KeePassXC  keepass.js:750:2
0 keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
Error 5: Timeout or not connected to KeePassXC  keepass.js:750:2
1  keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0 keepassxc-browser.js:1123
1  keepassxc-browser.js:1123
0  keepassxc-browser.js:1123
1 keepassxc-browser.js:1123
[...]
```

> Try to update to 0.3.1 which is just released

No changes, sorry.

**Comment by varjolintu** [comment]
Btw, the sources are updated today. And have you checked [these](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build) steps? That error is the only one displayed in the console and it means there's nothing to connect to.

**Comment by tcitworld** [comment]
Yeah, I just reinstalled the browser extension and cleared encryption keys and permissions. However, I notice that the checking status doesn't run forever, it timeouts and offers me to reload the Connection.
If I already have KeepassXC running, hitting reload doesn't do anything. However, it KeepassXC is properly closed, it opens and correctly fills or offers my passwords.

**Comment by varjolintu** [comment]
That's the way it works without a proxy application, KeePassXC cannot be running. The browser extension must start the process.

If KeePassXC was opened by the browser extension and then closed manually, the extension can detect such situation and offers a reload which starts KeePassXC again.

If you want to use the KeePassXC fork without browser extension doing to launching and exiting, you can use the proxy application.

**Comment by varjolintu** [comment]
Check the new RC2 build and report if the problem still exists.

**Comment by rdd2** [comment]
Right, I finally found some time to check again and it WORKS! I'll quickly document my status:
Updated sources
`git pull`
Configured
`cmake -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_BROWSER=ON -DCMAKE_BUILD_TYPE=Release ..`
Compiled
`make -j8`
Installed
`sudo make install`

Works great with with keepassxc-browser 0.3.2

**Comment by varjolintu** [comment]
Glad to hear it works!
