### ISSUE TITLE
Update to 0.3.0 closed KeePassXC

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#21]
Firefox Nightly (57.0a1 (2017-09-20)) on Windows 10 just updated the KeePassXC-Browser extension in the background from 0.2.9 to 0.3.0. After I approved the new permission request to access all data on all websites (and Firefox completed the update), KeePassXC (RC1-updated) was closed.
I'm not sure if it's possible to prevent this, but for me that was unexpected behavior.

**Comment by varjolintu** [comment]
Yes, this was unexpected to me as well. It seems when the permission request is approved the whole extension is reloaded. This causes KeePassXC to restart as the browser handles launching and terminating the process.
