### ISSUE TITLE
0.3.1 Stuck in "Checking Status"

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#23]
I'm using Firefox Nightly on Windows 10 with the updated RC1 of KeePassXC. Since the extension was updated to 0.3.1, KeePassXC-Browser can't connect to my database and is stuck in "Checking Status" forever.
There was no (noticeable) change to the Registry Keys and KeePassXC still launches with Firefox.
I manually downgraded to 0.3.0 from the addons.mozilla.org and the connection started working again as expected without any issues.

This is the debugging output:

> Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.  components.manifest:178
> Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:696:2
> Error 7: Cannot encrypt message or public key not found. Is Native Messaging enabled in KeePassXC?  keepass.js:750:2
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  socialwidgetloader.js:80:2
> TypeError: callback is not a function[Learn More]  keepass.js:548:3
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  background.js:5:173
> badger.heuristicBlocking is undefined heuristicblocking.js:508
> Server public key: gFGSVc1D1artluDwaAKHauc7WsZ8LpgqqlffOxQSZlM= keepass.js:546:4
> callback is not a function  keepass.js:548
> Error 1: Database not opened keepass.js:750:2
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Use of nsIFile in content process is deprecated. NetUtil.jsm:307:12
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/browser-polyfill.min.js
> Source Map URL: browser-polyfill.min.js.map[Learn More]  (unknown)
> Use of nsIFile in content process is deprecated. NetUtil.jsm:307:12
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/options/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map[Learn More]  (unknown)
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5
>   page.js:85:26
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.switchTab@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:69:2
> event.invoke/<@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:70:4
> promise callback*event.invoke@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/event.js:44:2
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:57:5
> promise callback*@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:52:2
>   page.js:69:76
> Error: Could not establish connection. Receiving end does not exist.
> Stack trace:
> Async*page.clearCredentials@moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/page.js:83:9
> @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:49:5

**Comment by varjolintu** [comment]
Thank you for reporting this. There's few issues with RC1 and this might be related to it. I will check the behavious with Windows.

**Comment by varjolintu** [comment]
Please check the new RC2 build :)

**Comment by whisdol** [comment]
Works with RC2, thanks!
