### ISSUE TITLE
Unable to fill in password on split username password pages on Firefox

### ISSUE THREAD

**Issue by takooakes** [varjolintu/keepassxc-browser#25]
My bank has a username page then goes to a new page where it asks for the password. I can get the username from keepassxc-browser, but on the next page keepassxc-browser gives me no option to fill in the password. This is on firefox on Mac OS.

**Comment by varjolintu** [comment]
Could you tell the page URL? Does the password generator icon get visible or can you enter your password if you redetect the credential fields from the popup? Or manually select your own fields?

**Comment by takooakes** [comment]
The url is usbank.com. The password generator icon is not visible and in the dropdown menu there is no entry for keepassxc-browser that I can manually select. It is an input box with type password. I'll look through the code at some point and see if I can figure it out.

**Comment by varjolintu** [comment]
What if you use the manual select but just skip the username field?

**Comment by takooakes** [comment]
I think the problem is that keepass-browser only adds options to the dropdown menu on the username input box. On pages without a username box there is nothing in the dropdown menu.

**Comment by varjolintu** [comment]
This same issue happens with a lot of pages. I'm going to investigate it.

**Comment by varjolintu** [comment]
There's no dropdown menu available but using a keyboard shortcut or Fill password through the context menu will work in the next release. Firefox doesn't show the context menu on password fields on the current stable release. If you want, you can use the develop branch codes to test the feature.

**Comment by varjolintu** [comment]
Fix for this is finally pushed to the develop branch. Please test it if it works the way it should.

Basically the fix does the following: if the page has only one input the extension checks if it's the password field. If it is, the dropdown menu is added to that field. You can also choose the correct login from the popup.

Please note that the latest Chrome/Chromium has some annoying popup displayed on the top of the dropdown menu that offers you to view all saved passwords. This happens even when you have the Chrome/Chromium password manager disabled completely.

**Comment by varjolintu** [comment]
Fixed with https://github.com/varjolintu/keepassxc-browser/commit/a00a07ae26fb353eff75337541e955ad446280cc.
