### ISSUE TITLE
KeePassXC Version: unknown

### ISSUE THREAD

**Issue by icf20** [varjolintu/keepassxc-browser#27]
for some reason the add-on dont detect keepassxc

`KeePassXC Version: unknown`

if i do check the version on terminal i get 
`keepassxc -v

keepassxc 2.2.1
`

**Comment by varjolintu** [comment]
You are not using this fork's release. keepassxc-browser is not yet officially supported in KeePassXC.

**Comment by icf20** [comment]
@varjolintu when does fork the fork get merged ?

**Comment by varjolintu** [comment]
To the 2.3.0 release. A date for that is still uncertain.
