### ISSUE TITLE
Cannot use on Firefox 56 - Ubuntu 17.10

### ISSUE THREAD

**Issue by dcardin** [varjolintu/keepassxc-browser#29]
Hello!

I hope I'm not missing something obvious... But I cannot get keepassxc to work from Firefox.

current setup: ubuntu 17.10
Firefox 56.0
keepassxc-browser: 0.3.4
keepassxc: KeePassXC-2.2.0-browser-rc3-x86_64.AppImage -> /usr/bin/keepassxc

I enabled the KeepassXC browser extension in keepassxc.
In the "Supported browsers" tab, I enabled Firefox (and Chrome)

But in FireFox, I always have the "Timeout or not connected" message.
My feeling is that the json file does not get installed. Any way I can run a command to know if it's installed in Firefox or not ?

Thanks

**Comment by dcardin** [comment]
I doubt that's relevant, but I get this message on the console:

> 1508200548872	addons.webextension.keepassxc-browser@sami.vanttinen	WARN	Please specify whether you want browser_style or not in your browser_action options.

**Comment by dcardin** [comment]
OK. I found the problem. My json file path attribute is completely wrong!

```
{
    "allowed_extensions": [
        "keepassxc-browser@sami.vanttinen"
    ],
    "description": "KeePassXC integration with Native Messaging support",
    "name": "com.varjolintu.keepassxc_browser",
    "path": "/tmp/.mount_keepasr3M6wl/usr/bin/keepassxc",
    "type": "stdio"
}
```

**Comment by varjolintu** [comment]
This is a known issue (I should really make list to the README). If you use an AppImage the binary is always ran from a temporary location which means the path in the JSON file is carbage. The only solutions are that you compile the sources yourself or use the [keepassxc-proxy](https://github.com/varjolintu/keepassxc-proxy) for the connection. If you want to use the proxy application you must make sure it is enabled from the Browser extension settings in KeePassXC.

**Comment by dcardin** [comment]
There actually is another solution. What I have done is moved my AppImage binary to /usr/bin/keepassxc and modified the path in the json file accordingly and it now works. 
I guess the problem will go away when this keepassxc fork is merged into master, then PPAs etc. can be used to get a traditionnal build into /usr/bin. 

Thanks!
