### ISSUE TITLE
KeePassXC keys vs Privacy

### ISSUE THREAD

**Issue by dcardin** [varjolintu/keepassxc-browser#30]
I usually have my Firefox delete everything after the session closes, for tracking/privacy reasons.
Where is the connection info to KeePassXC kept? Ie. what element in privacy should I prevent from cleaning-up on close if I want the browser and app to remain connected?

thanks

**Comment by varjolintu** [comment]
It's in the localStorage. I'm not actually even sure when Firefox does clear this, or does it get cleared at all.

**Comment by dcardin** [comment]
It does get cleared according to the "cookies" setting in privacy. Pretty sucky if you ask me.
Cookies is the #1 thing to remove to prevent tracking. Firefox should support both independently, but in the meantime there is an extension that allows you to remove cookies on tab close, which allows me to keep the cookies unselected. Poor man's solution. 

Tack, Sami :)
