### ISSUE TITLE
unable to connect to database firefox 56 win 10

### ISSUE THREAD

**Issue by dariopuerot** [varjolintu/keepassxc-browser#31]
When I click on the connect button in the connected databases section of the settings nothing happens.

I have the addon installed in two computers, this happens only in one of them.

both are win10 64bit and firefox 56

I have tried with keepassXC 2.2.1 and keepass XC 2.2.0 rc3 -browser

**Comment by varjolintu** [comment]
Official KeePassXC 2.2.1 is not supported with this feature. Only the releases from this fork (or the compiled source from the feature/chromeKeePassXC branch) will work.

Please check if the browser support is installed and check the registry and .json file content.

**Comment by dariopuerot** [comment]
Ok, now I have activated native messaging in keepassXC 2.2.0 browser, for firefox.

The connection still does not work.

This is the error shown by the firefox extension:
" keepassxc-browser has encountered an error:
Timeout or not connected to KeePassXC"

this are prints of  my keepassxc setup:
![image](https://user-images.githubusercontent.com/16033292/31738120-68e89486-b428-11e7-8b17-b609ee393bb4.png)
![image](https://user-images.githubusercontent.com/16033292/31738154-807f6a8e-b428-11e7-8ae4-0f338d32404b.png)

Information from debug info:
KeePassXC - Version 2.2.0
Revision: e88f5dca67b3d9499ca304a085abf45b9f1f45c8

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- KeePassHTTP
- Auto-Type
- Native Messaging browser extension

**Comment by varjolintu** [comment]
Could you check the following:
- Is com.varjolintu.keepassxc_browser.json created in the KeePassXC program folder?
- Is the path to the .json file visible at your registry at HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\ (there should be a folder under this with a default value as the path).

**Comment by dariopuerot** [comment]
Ok, now I have activated native messaging in keepassXC 2.2.0 browser, for firefox.

The connection still does not work.

This is the error shown by the firefox extension:
" keepassxc-browser has encountered an error:
Timeout or not connected to KeePassXC"

this are prints of  my keepassxc setup:
![image](https://user-images.githubusercontent.com/16033292/31738120-68e89486-b428-11e7-8b17-b609ee393bb4.png)
![image](https://user-images.githubusercontent.com/16033292/31738154-807f6a8e-b428-11e7-8ae4-0f338d32404b.png)

Information from debug info:
KeePassXC - Version 2.2.0
Revision: e88f5dca67b3d9499ca304a085abf45b9f1f45c8

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- KeePassHTTP
- Auto-Type
- Native Messaging browser extension

**Comment by dariopuerot** [comment]
There is no json file, but there is a registry value:
C:\Program Files\KeePassXC\com.varjolintu.keepassxc_browser_firefox.json

![image](https://user-images.githubusercontent.com/16033292/31789076-9fe0bb0e-b4ef-11e7-9f7f-feff9eca03bd.png)
![image](https://user-images.githubusercontent.com/16033292/31789112-caae7420-b4ef-11e7-9fd2-08150614505b.png)

**Comment by varjolintu** [comment]
Hmm. It seems that JSON file is not created. This might be a bug. That json file should be created from the Supported Browsers tab. In the meantime you can download [this](https://raw.githubusercontent.com/varjolintu/keepassxc-browser/master/com.varjolintu.keepassxc-browser-firefox-win.json) file to the KeePassXC program folder (to the same path the registry points) and rename the path parameter to "KeePassXC.exe".

**Comment by dariopuerot** [comment]
Just as a comment that may help: when trying to save the file in the keepassxc folder, windows tells me that I need administrator permission to do that, and does not let me. It is a funny message, because my user is administrator.
By copying the file from another folder and pasting, I have been able to place the file.

I saw that the file you sent me had normal hyphens and the one in the registry with low hyphens.

I changed that, and now the error message changed to no connected database, and keepasXC opened, asking for password.

I filled password and error message went to "You use an old version of KeePassXC.
Please download the latest version from keepassxc.org. " and has been checking status for more than five minutes now.

**Comment by dariopuerot** [comment]
Just as a comment that may help: when trying to save the file in the keepassxc folder, windows tells me that I need administrator permission to do that, and does not let me. It is a funny message, because my user is administrator.
By copying the file from another folder and pasting, I have been able to place the file.

I saw that the file you sent me had normal hyphens and the one in the registry with low hyphens.

I changed that, and now the error message changed to no connected database, and keepasXC opened, asking for password.

I filled password and error message went to "You use an old version of KeePassXC.
Please download the latest version from keepassxc.org. " and has been checking status for more than five minutes now.

**Comment by varjolintu** [comment]
Could you try to update to the RC4 release? It's been available since yesterday. Also the browser extension version 0.3.6 should be available.

**Comment by dariopuerot** [comment]
Now, after a reboot of firefox, it is working.  I did some before and nothing had happened, and now it is workin. Anyways I will update keeepasxc and addon

**Comment by varjolintu** [comment]
I forgot to mention that any changes to the JSON file or registry needs extension disable->enable or Firefox reboot. Sorry about that. Glad you got it working.
