### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by quthla** [varjolintu/keepassxc-browser#32]
Could you maybe release a portable version of the client as with the original KeepassXC? Thank you.

And are your changes planned to be merged with upstream some time?

**Comment by varjolintu** [comment]
I will soon. Thanks for the tip. At this point it seems the merge happens with KeePassXC 2.3.0 release. There are still some issues left that needs to be solved so the merging to their repo happens after that.

**Comment by quthla** [comment]
New release but no portable version yet or am I missing something?

**Comment by varjolintu** [comment]
Please wait a while. The last RC is almost done.

**Comment by varjolintu** [comment]
Check the latest [dev build](https://github.com/varjolintu/keepassxc/releases/tag/2.2.0-browser-dev191117)

**Comment by quthla** [comment]
Installed the extension in Chrome Portable on Windows but unable to connect to KeePassXC.
Tried to install the json file from KeePassXC settings page but not working as well probably due to portable Chrome.

Is there any way to manually install the native messaging manifest?

**Comment by quthla** [comment]
Got it working now manually. Would be nice if it worked automatically out of the box because if I move KeePassXC now, I have to update the path in the registry.

**Comment by varjolintu** [comment]
If you have been reading the release notes of the fork you have maybe noticed there's a new option in the Advanced tab of the Browser extension settings in KeePassXC. The option is `Update KeePassXC binary path automatically to Native Messaging scripts on startup`. But maybe that doesn't help in this case because now the scripts are always saved to user's temp folder. Which is incorrect because in portable builds you should save them to the KeePassXC binary path. Will fix this soon.

**Comment by quthla** [comment]
I already tried that option before but the only change is I get the error box twice instead of just once.
keepassxc.ini is located in the KeePassXC directory.

**Comment by varjolintu** [comment]
I made a fix that saves the scripts to the application folder instead of user's temp if the keepassxc-ini is located in the KeePassXC directory. Pushing the fix in tomorrow. Let's see if it helps.

**Comment by quthla** [comment]
Sounds good. Let me know when I can try.

**Comment by varjolintu** [comment]
The change has been checked in. Latest sources should work.

**Comment by quthla** [comment]
Tried latest release and it's working. Closing this.
