### ISSUE TITLE
Use Sentry to track errors

### ISSUE THREAD

**Issue by ishitatsuyuki** [varjolintu/keepassxc-browser#34]
I would like to suggest Sentry for tracking exceptions; I think there's many error handling missed and I frequently have it stuck in a broken state.

Feel free to close if you think it's overkill.

**Comment by varjolintu** [comment]
I have never even heard of this one! Thanks a lot.

**Comment by Mogost** [comment]
Sentry is very great tool. But using it in password manager extension is bad idea. In debug information can be sensitive data.

**Comment by ishitatsuyuki** [comment]
Sentry is able to scrub sensitive data to an extent; and the resulting reports are private anyway, so it's basically up to the author's policy.

**Comment by varjolintu** [comment]
An app or a library that could be used along with the extension itself (without any 3rd party service etc) would be the ideal solution. Or maybe just running some "test cases" would be enough. If you know any solutions like that, please let me know.

**Comment by Mogost** [comment]
In any case, the user should be able not to report errors.

**Comment by ishitatsuyuki** [comment]
What was the reason of closing this? Did we reach a conclusion?

**Comment by varjolintu** [comment]
Closing this because there are several PR's related to this (for example https://github.com/keepassxreboot/keepassxc-browser/pull/19), but still work-in-progress. Also, I'd like to close any issues from this old repository.
