### ISSUE TITLE
Timeout or not connected error

### ISSUE THREAD

**Issue by dazWiLLiE** [varjolintu/keepassxc-browser#35]
I can't get it to work.

First I installed keepassxc-browser-git from AUR in archlinux and the extension on latest Firefox (57), got "Timeout or not connected error".
Saw that it could be a mismatch between latest devel on keepassxc-browser and latest release on the extension, so I removed the package from AUR, and compiled the latest release of keepassxc-browser.
Same error. Searched for the .json files (for both Firefox and Chrome), they are created and points to /usr/bin/keepassxc (correct).

Checking the log in Firefoxm it says:
Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:799:2
Failed to connect: Unknown error  keepass.js:795:2
Error 5: Timeout or not connected to KeePassXC  keepass.js:855:2
Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:799:2
Failed to connect: Unknown error
TypeError: keepass.nativePort is null

That TypeError seems a bit.. off?

**Comment by varjolintu** [comment]
You mean you compiled the latest version of the KeePassXC fork with the feature/chromeKeePassXC branch? It should work if you built the correct branch with `-DWITH_XC_BROWSER=ON` option enabled.

**Comment by dazWiLLiE** [comment]
Yes, downloaded `2.2.0-browser-rc5` from [here](https://github.com/varjolintu/keepassxc/releases), and compiled it with `-DWITH_XC_BROWSER=ON` option enabled. I simply used the same compileflags from the AUR keepassxc-browser-git [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keepassxc-browser-git).
`Enable KeepassXC browser extension` is ticked, Chome and Firefox are selected, and the .json files are created and points to `/usr/bin/keepassxc`. Both keepassxc and Firefox are restarted, but still the same errormessage.. wonder what i'm missing?

**Comment by varjolintu** [comment]
So you are clearly using the fork without the proxy function. If so, please ensure that KeePassXC is not already running. Let the browser extension start the process.

If you want to use KeePassXC without launching the process from the browser, check the proxy option in the Advanced tab in the Settings.

**Comment by dazWiLLiE** [comment]
Yes, that was it. I had no idea that the extension was supposed to launch KeePassXC. I did experiment with that proxy option earlier, but got the same error message. Now off to test. Thanks!

**Comment by varjolintu** [comment]
Glad it works!
