### ISSUE TITLE
Merge this version with the official keepassxc

### ISSUE THREAD

**Issue by dehein** [varjolintu/keepassxc-browser#39]
Any chance, that your fork will be merged into the official version soon? 
Also your Windows compiled binary is not signed, so may be a security risk for some corporate antivirus software.

**Comment by varjolintu** [comment]
AFAIK the pull request is pending for the merge (all issues are solved). Hopefully we can see it soon in the [nighly builds](https://github.com/keepassxreboot/keepassxc/pull/1242).

**Comment by guillaume-uH57J9** [comment]
With that pull request merged, does that mean the official KeePassXC will support [Native Messaging](https://developer.mozilla.org/fr/Add-ons/WebExtensions/Native_messaging)? 

I'm currently using KeePassHTTP and hoping to switch to Native Messaging, as I understand it's more secure as it doesn't expose the password manager interface to every local user and apps.

**Comment by varjolintu** [comment]
@guillaume-uH57J9 Yes, that's what it means. Also, the support for KeePassHTTP will continue (at least for some time).

**Comment by GoodMirek** [comment]
I believe it is this PR: https://github.com/keepassxreboot/keepassxc/pull/608

**Comment by gardar** [comment]
Seems to be merged!

**Comment by varjolintu** [comment]
Yes! I'll still maintain my own fork because in the official version the native host name has changed. This is not compatible with the AMO version yet. Version 0.4.6 will be working with the official KeePassXC dev branch.

**Comment by guillaume-uH57J9** [comment]
That's exiting, getting closer to having a good UI/UX for the browser extension. 

keepassxc is a cool project that I'm happy to use, but usability isn't as good as I've used to see with keepass+keefox (autostart, excellent field detection, integration with the browser's password manager). 
My understanding is that it's mostly due to Firefox 57 which dropped/changed a lots of extension APIs.

**Comment by varjolintu** [comment]
There's now a transition perion ongoing. This means the official browser extension in AMO and Chrome Web Store has been upgraded to use new native messaging host name and UUID. Only a development build of KeePassXC is supported with these. Also the supported browser must be installed again from the Advanced settings.

If you still wish to use the older fork builds you have to use the renamed extension [keepass-browser-fork](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser-fork/) and it will not be updated anymore, and will be removed after the official repository page is opened under keepassxreboot.

**Comment by varjolintu** [comment]
@guillaume-uH57J9 There's some improvements coming to the usability, making it quicker and simpler. And you are correct, WebExtension transition removed a lot of things. For example you have no more acccess to the browser's password manager. KeeFox has been upgraded to [Kee](https://github.com/kee-org/browser-addon).
