### ISSUE TITLE
Making keepassxc-browser little bit modern

### ISSUE THREAD

**Issue by mauron85** [varjolintu/keepassxc-browser#4]
Hi. I decided to work on design and maybe new features for keepassxc-browser.
This is very first preview (static page, not working extension):

https://mauron85.github.io/keepassxc-browser/preview/

Written in react, material-io, supports internalization.

Want to hear, what you think.

**Comment by varjolintu** [comment]
Personally I'm not a fan of material design. I would make the theme closer to KeePassXC's theme (if there even is an official one). But the idea is still great. I have been thinking of rewriting (or recreating) a totally new plugin at some point. Even so, this kind of experimenting is very welcome and I appreciate it very much :)

**Comment by mauron85** [comment]
Not huge fan of material design either. But since Chrome 59 settings are also made in material design, keepassxc-browser will look more consistent with rest of chrome. Anyway material design is only part of the problem. My primary goal was to replace jquery spaghetti with something you should not worry extend without breaking something else. The options dialog is pretty much ready. I would like to also change popup dialog to something very simple, using only plain js.

There some things I find out during the process of rewrite, we can do better.

Bugs first:
* not possible to add more then one database
* popup detection of KeePassXC instance is running is very unreliable

Features:
* now all settings and `Specified credential fields` are stored localy in browser localStorage, which is not portable between multiple computers. It would be great if we can store settings directly in KeePassXC
* more to come...

**Comment by varjolintu** [comment]
Not possible to add more than one database? I have done most of the testing with two simultaneous databases. I agree the popup detection is unreliable and that's a thing I definitely like to improve. Retrieving statuses when KeePassXC is not running or database is not opened is still quite reliable. 
Luckily there's a lot of space for rewriting. The whole thing started as a fork but lot of things can be made much easier and prettier. I'm not fan of the jQuery spaghetti either :)

And yes, the whole thing lacks portability. There's always an option to use the browser's own sync methods but I agree storing the setting directly to KeePassXC is a better one. I will update these tasks to the Status thread. Big thanks!

**Comment by varjolintu** [comment]
@mauron85, did you notice that your settings page reports the KeePassXC version incorrectly? It says "Available KeePassXC: 2.1.5". There's no such version.

**Comment by mauron85** [comment]
The preview page is using mocking data and in case of extension I will check where from it comes from. Because I'm already lost. The passifox implementation is using too much messaging, changing html code of one page from another, global state... I found many issues there, but it's not worth reporting, it would never end. I though, that I would only replace options page and popup. But it's never gonna work reliable, without rewriting background scripts.

**Comment by varjolintu** [comment]
@mauron85, yes. It's a nice maze :)

**Comment by varjolintu** [comment]
@mauron85, I like what you are doing with the content scripts. Parsing the input forms looks really nice. Much more elegant without jQuery.
