### ISSUE TITLE
Cannot login to my webmail

### ISSUE THREAD

**Issue by achmetinternet** [varjolintu/keepassxc-browser#40]
My webmail or cpanel logins don't work for Hoststar, a Swiss provider, since the Login button doesn't respond anymore. Here is the URL:

https://webmail.hoststar.ch

**Comment by varjolintu** [comment]
Are you sure the extension is the reason login button doesn't respond? Disable the extension and verify this please.

**Comment by achmetinternet** [comment]
I did exactly that.

**Comment by varjolintu** [comment]
It seems that something in the extension removes the input form class `filled` and it causes the login button behaviour. Investigating.

**Comment by varjolintu** [comment]
Found the reason for this. There's a mylogin.min.js in the page that investigates all forms found in the page's source code. With the browser extension enabled there's the password generator inside the content script which holds an input field. That doesn't pass the checking of mylogin.min.js which has a function `fieldCheck()` that returns false if any input is found without the name `_user` or `_pass`. When the password generator input field is found the function returns false and disables the login button.

For now, a workaround for this is to disable the password generator from the extension's settings page. I'll write a fix that generates the password generator only when the icon is clicked, not before. It will solve the issue.

**Comment by varjolintu** [comment]
Fixed with https://github.com/varjolintu/keepassxc-browser/commit/a46787389910ae38a26fe8bfae1c0bb001156e46. New release 0.4.3 published.
