### ISSUE TITLE
File Not Found with Firefox ESR

### ISSUE THREAD

**Issue by gardar** [varjolintu/keepassxc-browser#41]
I'm getting a "404 file not found" when I try to run the keepassxc-browser extension on Firefox ESR 52.5
This is the url that the plugin prompts when I click it moz-extension://3e059bbb-6f08-451a-96f6-5d8694cb9054/popups/popup.html.

## General Info
KeePassXC fork - 2.2.0
keepassxc-browser - 0.4.3

Operating system: ArchLinux
Browser: Firefox ESR 52.5 (x64)
Proxy used: YES/NO

**Comment by varjolintu** [comment]
The minimum version of supported Firefox is 55. Or did AMO allowed you to install this to ESR?

**Comment by gardar** [comment]
Sorry about the late reply.
According to the readme I modified the manifest file and was able to load it into ESR.

> -The extension is supported with Firefox 55 and newer. If you want to load it as a temporary plugin with Firefox 54 or ESR you can just change the minimum version from the manifest file before loading it.

However you seem to have removed that part from the readme in commit  41f53cc10ca0b9f0b92b600622a5933b15c11021

**Comment by varjolintu** [comment]
I removed the part because I'm pretty certain some WebExtension API's are not supported with the ESR version.

**Comment by gardar** [comment]
Any chance ESR and/or Palemoon might gain support?

**Comment by varjolintu** [comment]
I'll see what I can do.

**Comment by varjolintu** [comment]
Well, Firefox supports WebExtensions and Palemoon doesn’t. There’s only two solutions for this: use a legacy keepasshttp based extension or stop using Palemoon.
