### ISSUE TITLE
Work together with @smorks

### ISSUE THREAD

**Issue by rugk** [varjolintu/keepassxc-browser#45]
I read [that](https://github.com/smorks/keepasshttp-connector/issues/49#issuecomment-348210373) from @smorks here:
> i am planning on changing how this extension works, to use Native Messaging to communicate with KeePass, rather than HTTP. it is supposed to be more secure than communicating over HTTP.

> KeePassXC already has this in the works, and i've been working on the KeePassHttp plugin for KeePass to work the same way, and there already is another browser extension that is working in this fashion too, which also has some of the bugs in mine already fixed.

That sounds a bit like you do duplicate work here. So you both have the same aim here and this is all about FLOSS, so why not work together?

Such password managers have [too stupid](https://github.com/smorks/keepasshttp-connector/issues/47) [problems](https://github.com/smorks/keepasshttp-connector/issues/42) anyway, so you should not duplicate the work.

Choose one add-on and work together, yeah? Maybe this one here (not tried, but newer codebase looks always good)

**Comment by smorks** [comment]
@varjolintu and i have already been in communication and have been working together to get this complete. he has been working on the KeePassXC side, where i've been working on the KeePass add-on (which is based on KeePassHttp, but I need a new name for it). i've been testing with his existing browser extension, and it's been working great.

**Comment by rugk** [comment]
So which browser extension will be the new one when it is finished? The one here in this repo or the "KeePassHttp" one (possibly renamed then, for obvious reasons)

**Comment by smorks** [comment]
yes, this one in this repo.

just to be clear, KeePassHttp is a Plugin for KeePass, and not a browser extension.

**Comment by rugk** [comment]
Yeah, I meant the connector. Such a complicated naming… 😃 
So good that the naming gets easier with "keepassxc-browser".

I am really looking forward to the result. It really looks like a huge step forward for KeePassX(C). 👍 

As for this issue, I think it is obsolete now.
