### ISSUE TITLE
Doesn't connect if keypassxc is already open. 

### ISSUE THREAD

**Issue by JoshuaPettus** [varjolintu/keepassxc-browser#46]
This project is really coming along,  but there is still one thing that just makes it awfully clunky. 

## Expected Behavior
Keypass-browser plugin should connect to keypassxc session if it's open or not.

## Current Behavior
If you open firefox while keypassxc is already open (could be in the database file, or could be at the opening screen, keypass-browser will not connect and says "Time-out or not connected to keypassxc", and offers to reload.  Reloading simply switches to the open keypassxc session, and does nothing.  

## Steps to Reproduce (for bugs)
1. Open KeypassXC
2. Open Firefox with keypass-browser installed
3. Notice how it says "Time-out or not connected to keypassxc."   
4. Click "reload" if you like

## General Info
KeePassXC fork - 2.2.4 though this has effected earlier versions as well
keepassxc-browser - 0.4.3 though this has effected earlier versions as well

Operating system: OSX
Browser: Firefox
Proxy used: No

**Comment by varjolintu** [comment]
The solution for this is to use the proxy feature that you can enable from Advanced tab in the KeePassXC settings.

If you are not using a proxy, native messaging needs to have a direct connection to the application it uses. In this situation it means the browser extension needs to start KeePassXC. If it's already open, single instance stuff hits it in and doesn't allow a second instance to launch.
