### ISSUE TITLE
Issues to connect keepassxc and browser extension 

### ISSUE THREAD

**Issue by truffe13** [varjolintu/keepassxc-browser#47]
## Informations 
on Linux I struggled to have a succesfull connection between keepassxc to the keepassxc-browser extension,
I compiled keepassxc from sources without any problem when but I tried to connect keepassxc-browser to keepassxc , I had the message : 
_"Cannot encrypt message or public key not found. Is Native Messaging enabled in KeePassXC? "_ 

Finally I re-compiled with the below options for cmake and **since it works well** (I have added the options -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON) 

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_XC_BROWSER=ON -DWITH_ASAN=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON ../

## General Info
KeePassXC fork - 2.2.4
keepassxc-browser - 0.4.4

Operating system: Linux 4.14.5-1-MANJARO #1 SMP
Browser: ff 57.0.2 (64 bits)
Proxy used: YES

Thanks to the team

**Comment by varjolintu** [comment]
Did you follow the steps in the [wiki](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-keepassxc-browser)?

**Comment by truffe13** [comment]
Yes , step by step , without any change.
But the wiki doesnt cover installation steps and I groped with the cmake options...

**Comment by varjolintu** [comment]
Where does the installed JSON scripts point to? Open `~/.mozilla/native-messaging-hosts/com.varjolintu.keepass_browser.json` and check the `path` variable.

If you want to run keepassxc and the proxy from the build folder you have to add the proxy path to the custom path variable in the Advanced settings. The proxy path should be `<build_folder>/src/proxy/keepassxc-proxy`. If you ran `make install` the proxy should be at `/usr/bin` because the option you used with cmake. There's also the option in the Advanced tab to locate the binaries automatically which you can also test.

**Comment by truffe13** [comment]
I have installed keepassxc to `/usr/local `by `make install` and using the cmake option `cmake -DCMAKE_INSTALL_PREFIX=/usr/local`

The installed JSON script contains the following (so it references  /usr/local" ) : 
```
{
    "allowed_extensions": [
        "keepassxc-browser@sami.vanttinen"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "com.varjolintu.keepassxc_browser",
    "path": "/usr/local/bin/keepassxc-proxy",
    "type": "stdio"
}
```
I checked all this before it before tweaking the compilation Options with  cmake and recompile it with 
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_XC_BROWSER=ON -DWITH_ASAN=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON ../` and since i use all these options  **keepassxc and the browser extension work well !!**

**Comment by varjolintu** [comment]
Did I understood correctly that now it works?

**Comment by truffe13** [comment]
yes correct, so may be you should add in the option some help to compile it correctlty 
something like 
After having downloaded the keepassxc source code and solved dependencies (refer to INSTALL.md)

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_XC_BROWSER=ON -DWITH_ASAN=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON ../
make
sudo make install
```

**Comment by varjolintu** [comment]
Actually in the branch where the feature exists, there are some instructions for this:
[https://github.com/varjolintu/keepassxc/tree/keepassxc-browser](https://github.com/varjolintu/keepassxc/tree/keepassxc-browser)

**Comment by truffe13** [comment]
yes I agree, I read them and I follow these instructions , but cmake instructions are unclear because too generic. It is stated :
`cmake -DWITH_TESTS=OFF ...and other options - see below...`
and below there are about 12 options that can be activated or not and there are no recommended options ...
There is why I strugged to has it working.

**Comment by varjolintu** [comment]
The list clearly says what options are enabled by default. There isn't official recommended options but usually the complete builds are with the first four options enabled.
