### ISSUE TITLE
Credential fetching does not work intermittently

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#48]
## Expected Behavior
Saved credentials for a website should load.

## Current Behavior
Sometimes when opening the login page via a link on a site (most recently noticed on news.ycombinator.com), KeePassXC-browser does not load my saved credentials. The login selection dropdown does not appear when I click in the login field. The "generate password"-icon is displayed in this case.

## Steps to Reproduce (for bugs)
Only happens intermittently, not sure how to reproduce. The issue disappears after a reload.

## Debug info
From the JS debug console:

Error --- keepassxc-browser.js:1200:59

​columnNumber: 1
​
fileName: "undefined"
​
lineNumber: 0
​
message: "Promised response from onMessage listener at @moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/background/init.js:77:1 went out of scope"
​
stack: "Async*cip.initCredentialFields/<@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1197:7\npromise callback*cip.initCredentialFields@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1175:2\npromise callback*cip.init@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1113:2\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1107:2\nj@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:29997\nDeferred/then/g/</k<@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:30313\nsetTimeout handler*Deferred/then/g/<@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:30520\ni@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28012\nfireWith@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28783\nfire@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28817\ni@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28012\nfireWith@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28783\nready@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:31932\nsetTimeout handler*@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:3:124\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:220\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:2\n"
​
__proto__: Object { … }

Error --- keepassxc-browser.js:1200:59
​
columnNumber: 1
​
fileName: "undefined"
​
lineNumber: 0
​
message: "Promised response from onMessage listener at @moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/background/init.js:77:1 went out of scope"
​
stack: "Async*cip.initCredentialFields/<@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1197:7\npromise callback*cip.initCredentialFields@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1175:2\nsetInterval handler*cip.detectNewActiveFields@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1122:20\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/keepassxc-browser.js:1108:2\nj@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:29997\nsetTimeout handler*Deferred/then/g/<@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:30520\ni@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28012\nfireWith@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28783\nfire@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28817\ni@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28012\nfireWith@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:28783\nready@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:31932\nsetTimeout handler*@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:3:124\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:220\n@moz-extension://0b65862f-d91a-1c45-aef8-684fde77e2bb/jquery-3.2.1.min.js:2:2\n"
​
__proto__: Object { … }

Line 1200 is this:
`
 			}).then(cip.retrieveCredentialsCallback).catch((e) => {console.log(e);});
`

## General Info
KeePassXC fork - RC7-updated
keepassxc-browser - 0.4.4

Operating system: macOS Sierra 10.12.6
Browser: Firefox Nightly 59.0a1 (2017-12-27) 
Proxy used: YES

**Comment by varjolintu** [comment]
Thanks. I'll investigate the issue.

**Comment by varjolintu** [comment]
Does this error still happen with the latest versions?

**Comment by whisdol** [comment]
This hasn't occured for me recently.

**Comment by varjolintu** [comment]
Glad to hear it. I haven't seen it either in my tests for a long time. Maybe the changes I made to 0.5.2 solved this one too.

**Comment by nspo** [comment]
I still have a similar problem. Password fetching does at some point stop to work, although the browser addon says "connected". When trying to "Fill User + Pass", it responds "No logins found". Sometimes it's also disconnected from KeepassXC, and I need to press "Connect" twice or more until it works. But even after that, it often has the problem that no logins are found. How can I offer debug information?

Only seems to happen on Ubuntu 17.10 with Chromium. Windows, Ubuntu 17.10 with Chrome (different computer) works well usually. Chromium and Addon are up-to-date.

**Comment by varjolintu** [comment]
You can try to debug the extension and see if there's any additional messages.

**Comment by varjolintu** [comment]
Those "message port closed" messages are happening because of the browser-polyfill.js (Mozilla's own library). So there's nothing to worry about.

For some reason, sometimes the content script is not seeing any URL that it could deliver when retrieving credentials. I still have no idea why and when this happens, but I will look into it.
