### ISSUE TITLE
Enhancement: Support multiple user name fields

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#49]
## Expected Behavior
Some sites, like the [online banking login from Deutsche Bank](https://meine.deutsche-bank.de/trxm/db/init.do?checkCookie) have multiple username fields. KeePassXC-Browser should support setting and filling a value for each of them.

## Current Behavior
Only one of the three fields can be set and filled as the username field.

## Possible Solution
I can think of two ways:
1) splitting the username entry in KeePassXC by a certain character like \<space\>, so in this case it could be "123 1234567 12". KeePassXC-Browser could then fill the three fields correspondingly.
2) setting separate values as "advanced" fields in KeePass. Users can then choose which value to use for which field with the "Choose own credential fields for this page"-wizard.

**Comment by whisdol** [comment]
Sure, that may be too much of an edge case to support. I'm also not aware of any other site that does this currently.

**Comment by varjolintu** [comment]
Have you tried using AutoType for pages like this?

**Comment by whisdol** [comment]
That's a good suggestion. After fiddeling with the auto type sequence, I got it working that way. Thank you!
This solution is certainly "good enough" for me and doesn't require further consideration.

**Comment by varjolintu** [comment]
Good to know! I'll keep the issue open because this kind of behaviour should be possible with StringFields. At least when you are choosing you own credential felds you can add some custom fields. But I failed to modify my test entry in a way those fields and values could be filled.

**Comment by varjolintu** [comment]
Now a few months later I fixed the bug with the StringFields. It will be in the next extension release. See: https://github.com/keepassxreboot/keepassxc-browser/pull/41.

**Comment by mestaritonttu** [comment]
How do we use these StringFields? When we pick the fields, the one after Password is shown as "String field #&#xfeff;1". I made a random attempt:

I went to Edit entry - Advanced and added an attribute with the name String field #&#xfeff;1. For the contents I set {NOTES}, to reference whatever string I have in the Notes field. However, nothing gets filled in the field in the browser.

**Comment by varjolintu** [comment]
@mestaritonttu Just make attributes to the entry starting with `KPH:`. These are filled in the order they are in the entry. No number needed.

**Comment by kronenpj** [comment]
@varjolintu - I'm afraid that's not enough information to help. Specifically what should a field name be to be filled in for a "String Field #1" entry? I've tried `KPH:Last Name`, `KPH:String`, etc.. None worked so far.

**Comment by varjolintu** [comment]
Use a space after the KPH:

**Comment by mestaritonttu** [comment]
To clarify: the stuff you have in the name after KPH: is not relevant because the only thing that matters is the order in which they appear in the Additional attributes entry box. Then for the attribute values just use whatever string you want directly.

**Comment by kronenpj** [comment]
Perfect, thanks for clarifying. For reference a site where this applies is https://aa.com/ they require a family name in addition to the usual username and password.
