### ISSUE TITLE
Unable to run headlessly if there's no graphical display.

### ISSUE THREAD

**Issue by michaelbarlow7** [varjolintu/keepassxc-browser#5]
As per https://news.ycombinator.com/item?id=14634975

Any attempt to run even `keepassxc --help` or `keepassxc --version` results in:
```
  QXcbConnection: Could not connect to display 
  Aborted
```
Additionally, although the [release notes for version 2.2.0](https://keepassxc.org/blog/2017-06-26-2.2.0-released/) mentions a command-line interface, it's unclear how to use it.

**Comment by varjolintu** [comment]
Dear sir, you opened an issue to a wrong repository. Did you mean [https://github.com/keepassxreboot/keepassxc/issues/](https://github.com/keepassxreboot/keepassxc/issues/)?

**Comment by michaelbarlow7** [comment]
Ah yes I did. Sorry about that!

**Comment by TheZ3ro** [comment]
It's already opened here https://github.com/keepassxreboot/keepassxc/issues/668
