### ISSUE TITLE
Stuck at 'Checking Status' on Chrome

### ISSUE THREAD

**Issue by EnKrypt** [varjolintu/keepassxc-browser#53]
The extension seems to broken since the update 3 days ago. This is not the same as issue #20 or issue #23 since this is happening on Chrome. There are no console logs when I inspect popup, and the icon is stuck at grey with a red cross at the corner.

## General Info
KeePassXC fork - 2.2.4
keepassxc-browser - 0.5.2

Operating system: Windows
Browser: Google Chrome
Proxy used: NO

**Comment by varjolintu** [comment]
The fork builds are no longer supported with the latest extension version. You need to compile the develop branch of the official KeePassXC by yourself. Or use the dev [releases](https://github.com/varjolintu/keepassxc/releases) (which are not up-to-date, missing few fixes). I'll try to update the dev releases soon. But AFAIK KeePassXC will also provide nightly builds soon.

**Comment by EnKrypt** [comment]
I'm sorry, in that case I may not be running a fork build. [This specific release is what I'm using](https://github.com/varjolintu/keepassxc/releases/tag/2.2.4-browser-final)

> And btw, you can debug the popups in Chrome when clicking it with the right mouse button and select Inspect Pop-up.

Did you read what I wrote above? I did inspect the popup. There is nothing being logged to console, not are there any network calls being made that error out.

**Comment by varjolintu** [comment]
Is there any difference if you run the latest build instead of the `final`? What about inspecting the background page from `chrome://extensions/` when it's on Developer mode. That should print something to the console.

**Comment by EnKrypt** [comment]
Running the latest build fixes this.

However, I think this is still not exactly a good thing, and could use some improvement.

Any time there is a release of the extension that is not backwards compatible with the version of the desktop app being used, issue some kind of warning so the user is aware would be nice.

Moreover, effort could be made to build a proper protocol that always remains backwards compatible. Breaking changes should never be introduced except for security patches that have no other workaround. Other breaking changes should be separated into a different protocol that exists alongside the older one so that existing, older clients do not break.

That is how I would do it at least, just my two cents.

**Comment by varjolintu** [comment]
These "rc" and "final" builds have been released under a transition period so there has been some non-compatibility between versions. If something has changed the message has been only seen in release notes. So yes, that could've been more visible. Still, the user base was not very large yet.

But now when the changes have been merged with the official version the protocol has remained unchanged. And in the future there will be clear notifications and explanations if anything changes.

I really appreciate your two cents. Thank you for the feedback!

**Comment by EnKrypt** [comment]
The updated version of the extension now claims that my version of KeePassXC is outdated. Previously I looked for releases with the `-browser` suffix, as I wanted the ones with the  Browser Integration menu in the settings. (not the legacy http server).

Which build should I install now?

**Comment by varjolintu** [comment]
Official KeePassXC.
