### ISSUE TITLE
Opera support

### ISSUE THREAD

**Issue by szyb** [varjolintu/keepassxc-browser#58]
KeepassHTTP support will be soon removed from KeepassXC, so I want to migrate to KeepassXC-browser. I use ChromeIPass extension (installed from Chrome webstore) and it works fine, while keepassXC-browser doesn't (see below: steps to reproduce)

## Current Behavior

When I install extension and setup it to work with keepassXC 2.3 it works fine, however when I restart system and open Opera it says "Timeout or not connected to KeePassXC". The only solution I know is to remove connection and set it up again. This is rather workaround than solution. 

## Possible Solution

Maybe develop and maintain native Opera extension and add it to their store? It should be very similar (if not 100% the same) with Chrome extension as Opera uses the same API (as far as I know)

## Steps to Reproduce (for bugs)

1. Installed "Install Chrome Extensions" extension (which allow Opera users to install extensions from Chrome webstore)
2. Installed "Keepassxc-browser" from Chrome webstore
3. Setup connection with Keepassxc 
4. Connection with Keepassxc works fine, until I shutdown the computer. After restart there is an error "Timeout or not connected to KeePassXC". 

EDIT: I see now closed issue #54. (Support for Opera). But in my case using "Install chrome extension" is not fully working. You can close the issue if you not planning to support Opera with or without the "install chrome extension"

## General Info
KeePassXC fork - 2.3.0
keepassxc-browser - 1.0

Operating system: Windows 10 Pro 1709, 16299.248
Browser: Opera
Proxy used: NO

**Comment by varjolintu** [comment]
See https://github.com/varjolintu/keepassxc-browser/issues/54.
