### ISSUE TITLE
Hotkey to fill in TOTP (Alt + Shift + T)

### ISSUE THREAD

**Issue by dperson** [varjolintu/keepassxc-browser#59]
When a page doesn't have the password field there is a hotkey (Alt + Shift + U) to fill in the username. If the password field isn't auto-detected there is a similar hotkey (Alt + Shift + P). Could you please add a Hotkey to fill in TOTP values (Alt + Shift + T being my suggestion)?

**Comment by varjolintu** [comment]
This is already done in the official repo.

**Comment by dperson** [comment]
Awesome, thank you!
