### ISSUE TITLE
Can't be installed in the latest Firefox Nightly

### ISSUE THREAD

**Issue by aindlq** [varjolintu/keepassxc-browser#6]
I've tried to install the extension from the https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/, but firefox complains that it is not compatible with the browser version. I'm using Firefox Nightly 56.0a1 (2017-06-27) (64-bit).

**Comment by varjolintu** [comment]
It seems there's an issue with Firefox loading the extension if the manifest has _strict_min_version_ with 56.0. If you download the extension source and change the _strict_min_version_ to 55.0 you can load the extension temporarily using page _about:debugging#addons_.

**Comment by aindlq** [comment]
Thanks!
