### ISSUE TITLE
Support username/password references

### ISSUE THREAD

**Issue by aindlq** [varjolintu/keepassxc-browser#7]
Latest keepassxc supports username/password references, see https://github.com/keepassxreboot/keepassxc/pull/370.

Would be great to have support for references in this extension, because currently, when reference is used in keepass, extension just fill username/password with the reference not with the value.

**Comment by varjolintu** [comment]
Done! I totally missed that when rewriting a certain class. I'm not building a new release yet so please get new sources and build them by yourself :)

**Comment by aindlq** [comment]
Thank you, works like a charm!
